### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by magnum7701** [lord-cyclone100/pokedex#10]
When we enter an invalid string or an invalid Pokemon name,  although an error is shown in console, no such message is shown on the webpage itself.

@lord-cyclone100  Kindly allow  me to resolve this issue under the "hacktoberfest" label.

**Comment by lord-cyclone100** [comment]
@magnum7701 I would suggest u to do the following instead:
+ When the user types an incorrect string, make the user redirect to an error page displaying thst no such pokemon found [https://dribbble.com/BiahXD/collections/3393381-pokedex](url)...like this....but dont make error 404 page. As u can see there is a pokeball representing the '0' in the 404. Try something similar. U may use pics, gifs, or any of ur own stuffs.

+ Add a return button to the same error page that would redirect the user to the index.html when he clicks on it.

+ Make the page responsive(Mobile first method is recommended but u can use anything u like).

Let me know if u are fine with these suggestions. Then I would assign u.

**Comment by magnum7701** [comment]
@lord-cyclone100  I am unable to open this dribble link

**Comment by lord-cyclone100** [comment]
![image](https://github.com/user-attachments/assets/92ce4e31-3a5a-496c-bfd6-01cc78299032)
like this @magnum7701

**Comment by magnum7701** [comment]
@lord-cyclone100  Understood. Working on it.

**Comment by lord-cyclone100** [comment]
go ahead @magnum7701 
pls fork the repo and make the contribution.

**Comment by lord-cyclone100** [comment]
@magnum7701 
How's the progress?
You have time till 23rd October

**Comment by magnum7701** [comment]
@lord-cyclone100 currently building the page
