### ISSUE TITLE
Enhance Hover Effects for Pokémon Content

### ISSUE THREAD

**Issue by ohmschrodinger** [lord-cyclone100/pokedex#7]
Currently, there are no hover effects for pokemon content. To improve user interaction and visual appeal, I propose the following enhancements:

- Increase Size on Hover: When a user hovers over a Pokémon card, the card should increase in size slightly to draw attention.

- Add Shadows: Incorporate shadows around the Pokémon cards on hover to create a depth effect, making the cards appear more prominent.

**Comment by lord-cyclone100** [comment]
@ohmschrodinger 
nice idea.....go ahead with ur contribution

**Comment by lord-cyclone100** [comment]
And one more thing......are u doing it for hacktoberfest ?
@ohmschrodinger

**Comment by ohmschrodinger** [comment]
Yes, this is for Hacktoberfest. Thanks! I’ll make sure to follow the tasks and guidelines next time.
